/**
 * Constantes da aplicação
 * Centralizadas em um único arquivo para fácil manutenção
 */

// USER ROLES
export const USER_ROLES = {
  CLIENT: 'CLIENT',
  ADMIN: 'ADMIN',
  SUPPLIER: 'SUPPLIER'
};

// ADDRESS TYPES
export const ADDRESS_TYPES = {
  BILLING: 'BILLING',
  SHIPPING: 'SHIPPING',
  BOTH: 'BOTH'
};

// ORDER STATUS
export const ORDER_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  PROCESSING: 'PROCESSING',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  RETURNED: 'RETURNED',
  REFUNDED: 'REFUNDED'
};

// PAYMENT STATUS
export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  APPROVED: 'APPROVED',
  DECLINED: 'DECLINED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
  PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED'
};

// PAYMENT METHODS
export const PAYMENT_METHODS = {
  CREDIT_CARD: 'CREDIT_CARD',
  DEBIT_CARD: 'DEBIT_CARD',
  PIX: 'PIX',
  BOLETO: 'BOLETO',
  WALLET: 'WALLET'
};

// COUPON TYPES
export const COUPON_TYPES = {
  PERCENTAGE: 'PERCENTAGE',
  FIXED: 'FIXED'
};

// SUPPLIER ORDER STATUS
export const SUPPLIER_ORDER_STATUS = {
  PENDING: 'PENDING',
  SENT_TO_SUPPLIER: 'SENT_TO_SUPPLIER',
  PROCESSING: 'PROCESSING',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED'
};

// PAGINATION
export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100
};

// VALIDATION REGEX
export const VALIDATION = {
  EMAIL: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  PHONE: /^(?:\+55|0)?(?:\(?\d{2}\)?)\s?\d{4,5}-?\d{4}$/,
  ZIP_CODE: /^\d{5}-?\d{3}$/,
  CPF: /^(\d{3}\.){2}\d{3}-\d{2}$/,
  CNPJ: /^(\d{2}\.){2}\d{3}-\d{2}$/,
  STRONG_PASSWORD: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/
};

// PASSWORDS
export const PASSWORD = {
  MIN_LENGTH: 8,
  SALT_ROUNDS: 10
};

// FILE UPLOAD
export const FILE_UPLOAD = {
  MAX_IMAGE_SIZE: 5 * 1024 * 1024, // 5MB
  ALLOWED_IMAGES: ['image/jpeg', 'image/png', 'image/webp'],
  MAX_IMAGES_PER_PRODUCT: 10
};

// HTTP STATUS CODES
export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500
};

// ERROR CODES
export const ERROR_CODES = {
  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  
  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  
  // Product
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  
  // Order
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  INVALID_ORDER_STATUS: 'INVALID_ORDER_STATUS',
  
  // Payment
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  
  // Coupon
  COUPON_NOT_FOUND: 'COUPON_NOT_FOUND',
  COUPON_EXPIRED: 'COUPON_EXPIRED',
  COUPON_ALREADY_USED: 'COUPON_ALREADY_USED',
  
  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  
  // Generic
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
};

// FEATURES
export const FEATURES = {
  DROPSHIPPING_ENABLED: true,
  REVIEWS_ENABLED: true,
  WISHLIST_ENABLED: true,
  MULTIPLE_ADDRESSES: true
};

// IMAGES
export const IMAGES = {
  PRODUCT_WIDTH: 800,
  PRODUCT_HEIGHT: 800,
  THUMBNAIL_WIDTH: 300,
  THUMBNAIL_HEIGHT: 300
};

export default {
  USER_ROLES,
  ADDRESS_TYPES,
  ORDER_STATUS,
  PAYMENT_STATUS,
  PAYMENT_METHODS,
  COUPON_TYPES,
  PAGINATION,
  VALIDATION,
  PASSWORD,
  FILE_UPLOAD,
  HTTP_STATUS,
  ERROR_CODES,
  FEATURES,
  IMAGES
};
